"""
Email delivery service for Trend Analysis reports.
"""
import logging
from typing import List, Dict
from datetime import datetime
from sources.gmail.client import GmailClient
from sources.models import TopicAnalysis, TrendValidation
from config import settings

logger = logging.getLogger(__name__)

class AnalysisEmailService:
    def __init__(self, gmail_client: GmailClient):
        self.gmail = gmail_client
        
    def _format_trend_row(self, trend: TrendValidation) -> str:
        """Format a single trend row for the email."""
        emoji = "📈" if trend.trend_direction == "rising" else "➖"
        if trend.trend_direction == "declining":
            emoji = "📉"
            
        audiences = []
        if "builder" in trend.audience_tags:
            audiences.append('<span style="background:#e0f2fe;color:#0369a1;padding:2px 6px;border-radius:10px;font-size:10px;text-transform:uppercase;">Builder</span>')
        if "founder" in trend.audience_tags:
            audiences.append('<span style="background:#f3e8ff;color:#7e22ce;padding:2px 6px;border-radius:10px;font-size:10px;text-transform:uppercase;">Founder</span>')
            
        audience_html = " ".join(audiences)
        
        return f"""
        <div style="margin-bottom: 16px; padding: 12px; border: 1px solid #eee; border-radius: 8px; background-color: #fafafa;">
            <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:4px;">
                <span style="font-weight:700; font-size:16px; color:#1a1a1a;">{trend.keyword}</span>
                <span style="font-weight:700; color:#8b3aed;">{trend.trend_score}/100</span>
            </div>
            <div style="display:flex; justify-content:space-between; align-items:center; font-size:12px; color:#666;">
                <span>{emoji} Momentum: {trend.momentum}%</span>
                <div>{audience_html}</div>
            </div>
            {f'<div style="margin-top:8px; font-size:11px; color:#888;">Context: {", ".join(trend.related_queries[:3])}</div>' if trend.related_queries else ''}
        </div>
        """

    def _generate_html_body(self, analyses: List[TopicAnalysis]) -> str:
        """Generate the HTML body for the email."""
        
        sections_html = ""
        
        for analysis in analyses:
            if not analysis.topics:
                continue
                
            source_label = analysis.source.replace("producthunt", "Product Hunt").replace("hackernews", "Hacker News").title()
            
            # Get top 3 topics
            top_topics = analysis.topics[:3]
            
            rows_html = "".join([self._format_trend_row(t) for t in top_topics])
            
            sections_html += f"""
            <div style="margin-bottom: 32px;">
                <h3 style="margin-bottom: 12px; font-family: 'Georgia', serif; color: #333; border-bottom: 2px solid #8b3aed; display: inline-block; padding-bottom: 4px;">
                    {source_label}
                </h3>
                {rows_html}
            </div>
            """
            
        return f"""
        <!DOCTYPE html>
        <html>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="text-align: center; margin-bottom: 40px;">
                <h1 style="font-family: 'Georgia', serif; font-size: 28px; margin-bottom: 8px; color: #1a1a1a;">Trend Intelligence</h1>
                <p style="color: #666; font-size: 14px; text-transform: uppercase; letter-spacing: 1px;">Market Validation Report</p>
            </div>
            
            {sections_html}
            
            <div style="margin-top: 40px; border-top: 1px solid #eee; padding-top: 20px; text-align: center; color: #999; font-size: 12px;">
                Generated by AI Content Agent • <a href="http://localhost:3000/analysis" style="color: #8b3aed; text-decoration: none;">View Dashboard</a>
            </div>
        </body>
        </html>
        """

    def send_analysis_email(self, analyses: List[TopicAnalysis]):
        """Send the aggregated analysis email."""
        if not analyses:
            logger.warning("No analyses to send")
            return
            
        html_content = self._generate_html_body(analyses)
        date_str = datetime.now().strftime("%b %d")
        subject = f"Trend Intelligence: Market Validation for {date_str}"
        
        recipient = settings.DIGEST_RECIPIENT_EMAIL
        self.gmail.send_html_email(
            to=recipient,
            subject=subject,
            html_content=html_content
        )
        logger.info(f"Sent analysis email to {recipient}")
